/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    CookingTimer: typeof import('./src/components/CookingTimer.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IngredientItem: typeof import('./src/components/IngredientItem.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
